# Generated by Django 4.1.7 on 2023-03-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Minha primeira postagem', max_length=255),
        ),
    ]
